#ifndef TASK_H
#define TASK_H

#import <Foundation/Foundation.h>
#import <CoreFoundation/CoreFoundation.h>


#define TASK_PERFORM_TOUCH 10
#define TASK_PROCESS_BRING_FOREGROUND 11
#define TASK_SHOW_ALERT_BOX 12
#define TASK_RUN_SHELL 13
#define TASK_TOUCH_RECORDING_START 14
#define TASK_TOUCH_RECORDING_STOP 15
#define TASK_CRAZY_TAP 16
#define TASK_RAPID_FIRE_TAP 17
#define TASK_USLEEP 18
#define TASK_PLAY_SCRIPT 19
#define TASK_PLAY_SCRIPT_FORCE_STOP 20
#define TASK_TEMPLATE_MATCH 21
#define TASK_SHOW_TOAST 22
#define TASK_COLOR_PICKER 23
#define TASK_TEXT_INPUT 24
#define TASK_GET_DEVICE_INFO 25
#define TASK_TOUCH_INDICATOR 26
#define TASK_TEXT_RECOGNIZER 27
#define TASK_COLOR_SEARCHER 28
#define TASK_PROMPT_INPUT 29
#define TASK_SCREENSHOT 30
#define TASK_DIALOG_CHOICE 31
#define TASK_OVERLAY 32
#define TASK_APP_KILL 33
#define TASK_APP_STATE 34
#define TASK_OPEN_URL 35
#define TASK_APP_CLEAR 36
#define TASK_KEYPRESS 37
#define TASK_VIBRATE 38
#define TASK_COLOR_MULTI 39
#define TASK_COLOR_PATTERN 40
#define TASK_IMAGE_REGION 41
#define TASK_RECORD_PLAY_EVENTS 42
#define TASK_RECORD_SAVE 43
#define TASK_RECORD_LOAD 44
#define TASK_IMAGE_MULTI 45
#define TASK_PING 46
#define TASK_CRANE 47
#define TASK_DEBUG_MARK 48
#define TASK_VALIDATE_SCRIPT 49
#define TASK_PLAY_SCRIPT_IN_PLACE 50
#define TASK_SETCELLULARDATA 51
#define TASK_SETAIRPLANEMODE 52
#define TASK_SETPROXY 53


#define TASK_UPDATE_CACHE 90

#define TASK_TEST 99

void processTask(UInt8 *buff, CFWriteStreamRef writeStreamRef = NULL);
static int getTaskType(UInt8* dataArray);

#endif
